# Generated by Django 5.0.6 on 2024-07-29 13:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_pricegroup'),
        ('services', '0002_company_category'),
        ('userprofile', '0007_userprofile_booking_interval_in_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='category',
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('basic', 'Basic'), ('additional', 'additional')], default='basic', max_length=255)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('service_timing', models.CharField(blank=True, max_length=255, null=True)),
                ('is_billable', models.BooleanField(default=False)),
                ('service_sku', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('basic_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='services.services')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_category', to='assets.categories')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_services', to='services.company')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to='userprofile.userprofile')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], default='fixed', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_price', to='services.services')),
            ],
            options={
                'verbose_name': 'Service Price',
                'verbose_name_plural': 'Service Prices',
            },
        ),
        migrations.CreateModel(
            name='BookingFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_booking_fields', to='services.services')),
            ],
            options={
                'verbose_name': 'Booking Field',
                'verbose_name_plural': 'Booking Fields',
            },
        ),
        migrations.DeleteModel(
            name='CompanyServices',
        ),
    ]
