# Generated by Django 5.0.6 on 2024-08-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_company_category_services_serviceprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service_type',
            new_name='t',
        ),
    ]
