# Generated by Django 5.0.6 on 2024-08-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_service_type_services_t'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='t',
            new_name='service_type',
        ),
    ]
