# Generated by Django 5.0.6 on 2024-08-25 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_services_is_free_services_keywords_services_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.CharField(choices=[('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('all', 'All')], default='All', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_slots', to='services.companystaff')),
            ],
            options={
                'verbose_name': 'Staff Slot',
                'verbose_name_plural': 'Staff Slots',
            },
        ),
    ]
