# Generated by Django 5.0.6 on 2024-08-26 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_staffslots'),
        ('userprofile', '0008_userprofile_is_payment_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffslots',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_slots', to='userprofile.userprofile'),
        ),
    ]
