# Generated by Django 5.0.6 on 2024-08-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_staffslots_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffslots',
            name='days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=255),
        ),
    ]
