# Generated by Django 5.0.6 on 2024-08-28 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_pricegroup'),
        ('services', '0009_alter_staffslots_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companystaff',
            name='staff_member',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_provider',
        ),
        migrations.AddField(
            model_name='companystaff',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companystaff',
            name='booking_interval_in_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='companystaff',
            name='calling_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_country_codes', to='assets.callingcodewithname'),
        ),
        migrations.AddField(
            model_name='companystaff',
            name='designation',
            field=models.CharField(choices=[('employee', 'Employee'), ('consultant', 'Consultant'), ('manager', 'Manager')], default='employee', max_length=255),
        ),
        migrations.AddField(
            model_name='companystaff',
            name='first_name',
            field=models.CharField(default='shamaas', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companystaff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_images/'),
        ),
        migrations.AddField(
            model_name='companystaff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companystaff',
            name='is_onsite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companystaff',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companystaff',
            name='last_name',
            field=models.CharField(default='shamas', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companystaff',
            name='nick_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companystaff',
            name='price_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_price_group', to='assets.pricegroup'),
        ),
        migrations.AddField(
            model_name='companystaff',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companystaff',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companystaff',
            name='work_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='service_providers',
            field=models.ManyToManyField(related_name='service_providers', to='services.companystaff'),
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_contacts', to='services.companystaff')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_break_time', models.TimeField(blank=True, null=True)),
                ('end_break_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_schedule', to='services.companystaff')),
            ],
            options={
                'verbose_name': 'Work Schedule',
                'verbose_name_plural': 'Work Schedules',
            },
        ),
        migrations.DeleteModel(
            name='StaffSlots',
        ),
    ]
