# Generated by Django 5.0.6 on 2024-07-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_useractivation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_validation_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
