# Generated by Django 5.0.6 on 2025-01-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_logentry_created_at_logentry_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='date',
        ),
    ]
