# Generated by Django 5.0.6 on 2024-07-04 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_and_subscription', '0002_subscription_created_at_subscription_updated_at_and_more'),
        ('userprofile', '0005_userprofile_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('payment_amount', models.CharField(max_length=255)),
                ('payment_currency', models.CharField(max_length=255)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_refund', models.BooleanField(default=False)),
                ('payment_resource_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payment', to='payments_and_subscription.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_intent', to='userprofile.userprofile')),
            ],
            options={
                'verbose_name': 'Payment Detail',
                'verbose_name_plural': 'Payment Details',
            },
        ),
        migrations.CreateModel(
            name='PayPalUserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paypal_email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_user_details', to='userprofile.userprofile')),
            ],
            options={
                'verbose_name': 'Paypal User Detail',
                'verbose_name_plural': 'Paypal User Details',
            },
        ),
    ]
