# Generated by Django 5.0.6 on 2024-08-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bookings_user'),
        ('payments_and_subscription', '0004_alter_subscriptionfeature_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_payment', to='booking.bookings'),
        ),
    ]
