# Generated by Django 5.0.6 on 2024-09-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_and_subscription', '0005_paymentdetails_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionfeature',
            name='feature_status',
            field=models.BooleanField(default=True),
        ),
    ]
