# Generated by Django 5.0.6 on 2024-07-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_city_userprofile_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='inactive', max_length=255),
        ),
    ]
