# Generated by Django 5.0.6 on 2024-07-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategories',
        ),
    ]
