# Generated by Django 4.2.15 on 2024-10-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_pricegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
