# Generated by Django 5.0.6 on 2025-01-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_categories_description'),
        ('booking', '0011_remove_journals_diagnosis_remove_journals_kvy_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_time_in_days', models.IntegerField(blank=True, null=True)),
                ('form_title', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('surename', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Forms',
                'db_table': 'forms',
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('shortcut', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_case', models.CharField(blank=True, max_length=255, null=True)),
                ('assessment', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='templates/images/')),
                ('template_type', models.CharField(choices=[('text', 'text'), ('phrase', 'phrase'), ('drawing', 'drawing'), ('image', 'image'), ('marker', 'marker')], default='text', max_length=255)),
                ('diagnosis', models.ManyToManyField(blank=True, related_name='templates', to='booking.diagnosis')),
                ('kva_code', models.ManyToManyField(blank=True, related_name='templates', to='booking.kvacodes')),
            ],
            options={
                'verbose_name_plural': 'Templates',
                'db_table': 'templates',
            },
        ),
    ]
