# Generated by Django 5.0.6 on 2025-01-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_forms_templates'),
        ('booking', '0012_alter_journals_kvy_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='kva_code',
            field=models.ManyToManyField(blank=True, related_name='kvy_templates', to='booking.kvycodes'),
        ),
    ]
