# Generated by Django 5.0.6 on 2024-08-12 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0005_rename_t_services_service_type'),
        ('userprofile', '0008_userprofile_is_payment_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('booking_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=255)),
                ('payment_type', models.CharField(choices=[('on_the_spot', 'On The Spot'), ('card_payment', 'Card Payment'), ('online_payment', 'Online Payment'), ('wallet_payment', 'Wallet Payment'), ('other', 'Other')], default='on_the_spot', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='services.services')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to='userprofile.userprofile')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='bookings_id_cd3274_idx'), models.Index(fields=['-created_at'], name='bookings_created_8ec366_idx')],
            },
        ),
    ]
