# Generated by Django 5.0.6 on 2024-08-25 18:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_bookings_booking_date_and_more'),
        ('services', '0006_services_is_free_services_keywords_services_price_and_more'),
        ('userprofile', '0008_userprofile_is_payment_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_feedback', to='booking.bookings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_feedback', to='userprofile.userprofile')),
            ],
            options={
                'verbose_name': 'Client Feedback',
                'verbose_name_plural': 'Client Feedback',
                'db_table': 'client_feedback',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='client_feed_id_ad2714_idx'), models.Index(fields=['-created_at'], name='client_feed_created_93e003_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_feedback', to='services.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_feedback', to='userprofile.userprofile')),
            ],
            options={
                'verbose_name': 'Service Feedback',
                'verbose_name_plural': 'Service Feedback',
                'db_table': 'service_feedback',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='service_fee_id_1d5888_idx'), models.Index(fields=['-created_at'], name='service_fee_created_067bdb_idx')],
            },
        ),
    ]
