# Generated by Django 5.0.6 on 2024-08-25 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_clientfeedback_servicefeedback'),
        ('services', '0007_staffslots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefeedback',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_feedback', to='services.company'),
        ),
    ]
