# Generated by Django 5.0.6 on 2024-09-05 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_bookings_booking_description_bookings_phone'),
        ('userprofile', '0009_remove_userprofile_booking_interval_in_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_owner', to='userprofile.userprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_user', to='userprofile.userprofile')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'db_table': 'journals',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='journals_id_3a947e_idx'), models.Index(fields=['-created_at'], name='journals_created_900dfc_idx')],
            },
        ),
    ]
