# Generated by Django 5.0.6 on 2025-01-03 18:14

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_bookings_end_booking_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journals',
            name='email',
        ),
        migrations.RemoveField(
            model_name='journals',
            name='name',
        ),
        migrations.AddField(
            model_name='journals',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journals',
            name='assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journals',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_journal', to='booking.bookings'),
        ),
        migrations.AddField(
            model_name='journals',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journals',
            name='date',
            field=models.DateField(default="2025-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journals',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journals',
            name='kvy_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journals',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
