# Generated by Django 5.0.6 on 2025-01-04 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_journals_email_remove_journals_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journals',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='journals',
            name='kvy_code',
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnosis',
                'db_table': 'diagnosis',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='diagnosis_id_22ac2c_idx'), models.Index(fields=['-created_at'], name='diagnosis_created_87fe95_idx')],
            },
        ),
        migrations.CreateModel(
            name='KVYCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'KVY Code',
                'verbose_name_plural': 'KVY Codes',
                'db_table': 'kvy_codes',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='kvy_codes_id_079275_idx'), models.Index(fields=['-created_at'], name='kvy_codes_created_07eeb2_idx')],
            },
        ),
        migrations.AddField(
            model_name='journals',
            name='diagnosis',
            field=models.ManyToManyField(blank=True, related_name='diagnosis_journal', to='booking.diagnosis'),
        ),
        migrations.AddField(
            model_name='journals',
            name='kvy_code',
            field=models.ManyToManyField(blank=True, related_name='kvy_journal', to='booking.kvycodes'),
        ),
        migrations.CreateModel(
            name='JournalFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='journals/files/')),
                ('is_active', models.BooleanField(default=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_files', to='booking.journals')),
            ],
            options={
                'verbose_name': 'Journal File',
                'verbose_name_plural': 'Journal Files',
                'db_table': 'journal_files',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='journal_fil_id_3d5a83_idx'), models.Index(fields=['-created_at'], name='journal_fil_created_a080b3_idx')],
            },
        ),
    ]
