# Generated by Django 5.0.6 on 2025-01-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_journals_diagnosis_remove_journals_kvy_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='kvy_code',
            field=models.ManyToManyField(blank=True, related_name='kvy_journal_code', to='booking.kvycodes'),
        ),
    ]
