# Generated by Django 5.0.6 on 2025-01-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_forms_templates'),
        ('booking', '0011_remove_journals_diagnosis_remove_journals_kvy_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KVYCodes',
            new_name='KVACodes',
        ),
        migrations.AlterModelOptions(
            name='kvacodes',
            options={'ordering': ['-id'], 'verbose_name': 'KVA Code', 'verbose_name_plural': 'KVA Codes'},
        ),
        migrations.RenameIndex(
            model_name='kvacodes',
            new_name='kva_codes_id_956edc_idx',
            old_name='kvy_codes_id_079275_idx',
        ),
        migrations.RenameIndex(
            model_name='kvacodes',
            new_name='kva_codes_created_0b5435_idx',
            old_name='kvy_codes_created_07eeb2_idx',
        ),
        migrations.AlterModelTable(
            name='kvacodes',
            table='kva_codes',
        ),
    ]
