# Generated by Django 5.0.6 on 2024-07-04 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('userprofile', '0003_userprofile_calling_code_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cities', to='assets.cities'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_currency', to='assets.currency'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_timezones', to='assets.countrytimezone'),
        ),
    ]
