# Generated by Django 5.0.6 on 2024-08-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_userprofile_is_payment_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='booking_interval_in_minutes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_onsite',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='online_booking_available',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='onsite_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='price_group',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='work_from',
        ),
    ]
